; https://tcl.tk/man/tcl8.7/TclCmd/index.html

;  argc                     ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  argv                     ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  argv0                    ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  auto_path                ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  env                      ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  errorCode                ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  errorInfo                ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_interactive          ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_library              ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_nonwordchars         ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_patchLevel           ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_pkgPath              ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_platform             ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_precision            ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_rcFileName           ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_traceCompile         ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_traceExec            ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_version              ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html
;  tcl_wordchars            ; https://tcl.tk/man/tcl8.7/TclCmd/tclvars.html

;  auto_execok              ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  auto_import              ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  auto_load                ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  auto_mkindex             ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  auto_qualify             ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  auto_reset               ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  parray                   ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  tcl_endOfWord            ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  tcl_findLibrary          ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  tcl_startOfNextWord      ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  tcl_startOfPreviousWord  ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  tcl_wordBreakAfter       ; https://tcl.tk/man/tcl8.7/TclCmd/library.html
;  tcl_wordBreakBefore      ; https://tcl.tk/man/tcl8.7/TclCmd/library.html

;  coroinject               ; https://tcl.tk/man/tcl8.7/TclCmd/coroutine.html
;  coroprobe                ; https://tcl.tk/man/tcl8.7/TclCmd/coroutine.html
;  coroutine                ; https://tcl.tk/man/tcl8.7/TclCmd/coroutine.html
;  yield                    ; https://tcl.tk/man/tcl8.7/TclCmd/coroutine.html
;  yieldto                  ; https://tcl.tk/man/tcl8.7/TclCmd/coroutine.html

;  after                    ; https://tcl.tk/man/tcl8.7/TclCmd/after.html
;  append                   ; https://tcl.tk/man/tcl8.7/TclCmd/append.html
;  apply                    ; https://tcl.tk/man/tcl8.7/TclCmd/apply.html
;  array                    ; https://tcl.tk/man/tcl8.7/TclCmd/array.html
;  bgerror                  ; https://tcl.tk/man/tcl8.7/TclCmd/bgerror.html
;  binary                   ; https://tcl.tk/man/tcl8.7/TclCmd/binary.html
;  break                    ; https://tcl.tk/man/tcl8.7/TclCmd/break.html
;  callback                 ; https://tcl.tk/man/tcl8.7/TclCmd/callback.html
;  catch                    ; https://tcl.tk/man/tcl8.7/TclCmd/catch.html
;  cd                       ; https://tcl.tk/man/tcl8.7/TclCmd/cd.html
;  chan                     ; https://tcl.tk/man/tcl8.7/TclCmd/chan.html
;  classvariable            ; https://tcl.tk/man/tcl8.7/TclCmd/classvariable.html
;  clock                    ; https://tcl.tk/man/tcl8.7/TclCmd/clock.html
;  close                    ; https://tcl.tk/man/tcl8.7/TclCmd/close.html
;  concat                   ; https://tcl.tk/man/tcl8.7/TclCmd/concat.html
;  continue                 ; https://tcl.tk/man/tcl8.7/TclCmd/continue.html
;  cookiejar                ; https://tcl.tk/man/tcl8.7/TclCmd/cookiejar.html
;  dde                      ; https://tcl.tk/man/tcl8.7/TclCmd/dde.html
;  dict                     ; https://tcl.tk/man/tcl8.7/TclCmd/dict.html
;  encoding                 ; https://tcl.tk/man/tcl8.7/TclCmd/encoding.html
;  eof                      ; https://tcl.tk/man/tcl8.7/TclCmd/eof.html
;  error                    ; https://tcl.tk/man/tcl8.7/TclCmd/error.html
;  eval                     ; https://tcl.tk/man/tcl8.7/TclCmd/eval.html
;  exec                     ; https://tcl.tk/man/tcl8.7/TclCmd/exec.html
;  exit                     ; https://tcl.tk/man/tcl8.7/TclCmd/exit.html
;  expr                     ; https://tcl.tk/man/tcl8.7/TclCmd/expr.html
;  fblocked                 ; https://tcl.tk/man/tcl8.7/TclCmd/fblocked.html
;  fconfigure               ; https://tcl.tk/man/tcl8.7/TclCmd/fconfigure.html
;  fcopy                    ; https://tcl.tk/man/tcl8.7/TclCmd/fcopy.html
;  file                     ; https://tcl.tk/man/tcl8.7/TclCmd/file.html
;  fileevent                ; https://tcl.tk/man/tcl8.7/TclCmd/fileevent.html
;  filename                 ; https://tcl.tk/man/tcl8.7/TclCmd/filename.html
;  flush                    ; https://tcl.tk/man/tcl8.7/TclCmd/flush.html
;  for                      ; https://tcl.tk/man/tcl8.7/TclCmd/for.html
;  foreach                  ; https://tcl.tk/man/tcl8.7/TclCmd/foreach.html
;  format                   ; https://tcl.tk/man/tcl8.7/TclCmd/format.html
;  fpclassify               ; https://tcl.tk/man/tcl8.7/TclCmd/fpclassify.html
;  gets                     ; https://tcl.tk/man/tcl8.7/TclCmd/gets.html
;  glob                     ; https://tcl.tk/man/tcl8.7/TclCmd/glob.html
;  global                   ; https://tcl.tk/man/tcl8.7/TclCmd/global.html
;  history                  ; https://tcl.tk/man/tcl8.7/TclCmd/history.html
;  http                     ; https://tcl.tk/man/tcl8.7/TclCmd/http.html
;  if                       ; https://tcl.tk/man/tcl8.7/TclCmd/if.html
;  incr                     ; https://tcl.tk/man/tcl8.7/TclCmd/incr.html
;  info                     ; https://tcl.tk/man/tcl8.7/TclCmd/info.html
;  interp                   ; https://tcl.tk/man/tcl8.7/TclCmd/interp.html
;  join                     ; https://tcl.tk/man/tcl8.7/TclCmd/join.html
;  lappend                  ; https://tcl.tk/man/tcl8.7/TclCmd/lappend.html
;  lassign                  ; https://tcl.tk/man/tcl8.7/TclCmd/lassign.html
;  lindex                   ; https://tcl.tk/man/tcl8.7/TclCmd/lindex.html
;  link                     ; https://tcl.tk/man/tcl8.7/TclCmd/link.html
;  linsert                  ; https://tcl.tk/man/tcl8.7/TclCmd/linsert.html
;  list                     ; https://tcl.tk/man/tcl8.7/TclCmd/list.html
;  llength                  ; https://tcl.tk/man/tcl8.7/TclCmd/llength.html
;  lmap                     ; https://tcl.tk/man/tcl8.7/TclCmd/lmap.html
;  load                     ; https://tcl.tk/man/tcl8.7/TclCmd/load.html
;  lpop                     ; https://tcl.tk/man/tcl8.7/TclCmd/lpop.html
;  lrange                   ; https://tcl.tk/man/tcl8.7/TclCmd/lrange.html
;  lremove                  ; https://tcl.tk/man/tcl8.7/TclCmd/lremove.html
;  lrepeat                  ; https://tcl.tk/man/tcl8.7/TclCmd/lrepeat.html
;  lreplace                 ; https://tcl.tk/man/tcl8.7/TclCmd/lreplace.html
;  lreverse                 ; https://tcl.tk/man/tcl8.7/TclCmd/lreverse.html
;  lsearch                  ; https://tcl.tk/man/tcl8.7/TclCmd/lsearch.html
;  lset                     ; https://tcl.tk/man/tcl8.7/TclCmd/lset.html
;  lsort                    ; https://tcl.tk/man/tcl8.7/TclCmd/lsort.html
;  mathfunc                 ; https://tcl.tk/man/tcl8.7/TclCmd/mathfunc.html
;  mathop                   ; https://tcl.tk/man/tcl8.7/TclCmd/mathop.html
;  memory                   ; https://tcl.tk/man/tcl8.7/TclCmd/memory.html
;  msgcat                   ; https://tcl.tk/man/tcl8.7/TclCmd/msgcat.html
;  my                       ; https://tcl.tk/man/tcl8.7/TclCmd/my.html
;  myclass                  ; https://tcl.tk/man/tcl8.7/TclCmd/my.html
;  mymethod                 ; https://tcl.tk/man/tcl8.7/TclCmd/callback.html
;  namespace                ; https://tcl.tk/man/tcl8.7/TclCmd/namespace.html
;  next                     ; https://tcl.tk/man/tcl8.7/TclCmd/next.html
;  nextto                   ; https://tcl.tk/man/tcl8.7/TclCmd/next.html

;  oo::abstract             ; https://tcl.tk/man/tcl8.7/TclCmd/abstract.html
;  oo::class                ; https://tcl.tk/man/tcl8.7/TclCmd/class.html
;  oo::copy                 ; https://tcl.tk/man/tcl8.7/TclCmd/copy.html
;  oo::define               ; https://tcl.tk/man/tcl8.7/TclCmd/define.html
;  oo::objdefine            ; https://tcl.tk/man/tcl8.7/TclCmd/define.html
;  oo::object               ; https://tcl.tk/man/tcl8.7/TclCmd/object.html
;  oo::singleton            ; https://tcl.tk/man/tcl8.7/TclCmd/singleton.html

;  open                     ; https://tcl.tk/man/tcl8.7/TclCmd/open.html
;  package                  ; https://tcl.tk/man/tcl8.7/TclCmd/package.html
;  pid                      ; https://tcl.tk/man/tcl8.7/TclCmd/pid.html
;  pkg_mkIndex              ; https://tcl.tk/man/tcl8.7/TclCmd/pkgMkIndex.html
;  pkg::create              ; https://tcl.tk/man/tcl8.7/TclCmd/packagens.html

;  platform                 ; https://tcl.tk/man/tcl8.7/TclCmd/platform.html
;  platform::shell          ; https://tcl.tk/man/tcl8.7/TclCmd/platform_shell.html

;  proc                     ; https://tcl.tk/man/tcl8.7/TclCmd/proc.html
;  puts                     ; https://tcl.tk/man/tcl8.7/TclCmd/puts.html
;  pwd                      ; https://tcl.tk/man/tcl8.7/TclCmd/pwd.html
;  re_syntax                ; https://tcl.tk/man/tcl8.7/TclCmd/re_syntax.html
;  read                     ; https://tcl.tk/man/tcl8.7/TclCmd/read.html
;  refchan                  ; https://tcl.tk/man/tcl8.7/TclCmd/refchan.html
;  regexp                   ; https://tcl.tk/man/tcl8.7/TclCmd/regexp.html
;  registry                 ; https://tcl.tk/man/tcl8.7/TclCmd/registry.html
;  regsub                   ; https://tcl.tk/man/tcl8.7/TclCmd/regsub.html
;  rename                   ; https://tcl.tk/man/tcl8.7/TclCmd/rename.html
;  return                   ; https://tcl.tk/man/tcl8.7/TclCmd/return.html
;  safe                     ; https://tcl.tk/man/tcl8.7/TclCmd/safe.html
;  scan                     ; https://tcl.tk/man/tcl8.7/TclCmd/scan.html
;  seek                     ; https://tcl.tk/man/tcl8.7/TclCmd/seek.html
;  self                     ; https://tcl.tk/man/tcl8.7/TclCmd/self.html
;  set                      ; https://tcl.tk/man/tcl8.7/TclCmd/set.html
;  socket                   ; https://tcl.tk/man/tcl8.7/TclCmd/socket.html
;  source                   ; https://tcl.tk/man/tcl8.7/TclCmd/source.html
;  split                    ; https://tcl.tk/man/tcl8.7/TclCmd/split.html
;  string                   ; https://tcl.tk/man/tcl8.7/TclCmd/string.html
;  subst                    ; https://tcl.tk/man/tcl8.7/TclCmd/subst.html
;  switch                   ; https://tcl.tk/man/tcl8.7/TclCmd/switch.html
;  tailcall                 ; https://tcl.tk/man/tcl8.7/TclCmd/tailcall.html
;  Tcl                      ; https://tcl.tk/man/tcl8.7/TclCmd/Tcl.html

;  tcl::idna                ; https://tcl.tk/man/tcl8.7/TclCmd/idna.html
;  tcl::prefix              ; https://tcl.tk/man/tcl8.7/TclCmd/prefix.html
;  tcl::process             ; https://tcl.tk/man/tcl8.7/TclCmd/process.html

;  tcltest                  ; https://tcl.tk/man/tcl8.7/TclCmd/tcltest.html
;  tell                     ; https://tcl.tk/man/tcl8.7/TclCmd/tell.html
;  throw                    ; https://tcl.tk/man/tcl8.7/TclCmd/throw.html
;  time                     ; https://tcl.tk/man/tcl8.7/TclCmd/time.html
;  timerate                 ; https://tcl.tk/man/tcl8.7/TclCmd/timerate.html
;  tm                       ; https://tcl.tk/man/tcl8.7/TclCmd/tm.html
;  trace                    ; https://tcl.tk/man/tcl8.7/TclCmd/trace.html
;  transchan                ; https://tcl.tk/man/tcl8.7/TclCmd/transchan.html
;  try                      ; https://tcl.tk/man/tcl8.7/TclCmd/try.html
;  unknown                  ; https://tcl.tk/man/tcl8.7/TclCmd/unknown.html
;  unload                   ; https://tcl.tk/man/tcl8.7/TclCmd/unload.html
;  unset                    ; https://tcl.tk/man/tcl8.7/TclCmd/unset.html
;  update                   ; https://tcl.tk/man/tcl8.7/TclCmd/update.html
;  uplevel                  ; https://tcl.tk/man/tcl8.7/TclCmd/uplevel.html
;  upvar                    ; https://tcl.tk/man/tcl8.7/TclCmd/upvar.html
;  variable                 ; https://tcl.tk/man/tcl8.7/TclCmd/variable.html
;  vwait                    ; https://tcl.tk/man/tcl8.7/TclCmd/vwait.html
;  while                    ; https://tcl.tk/man/tcl8.7/TclCmd/while.html
;  zipfs                    ; https://tcl.tk/man/tcl8.7/TclCmd/zipfs.html
;  zlib                     ; https://tcl.tk/man/tcl8.7/TclCmd/zlib.html
